### ISSUE TITLE
Fatal error: Call to a member function withBody on null

### ISSUE THREAD

**Issue by lindyhopchris** [middlewares/proxy#1]
Hi! Thanks for the package.

I think there's a problem with how the proxy handles an exception scenario. These lines:
https://github.com/middlewares/proxy/blob/master/src/Proxy.php#L85-L88

If a `RequestException` is thrown, it is caught and the response is set using `getResponse()`.  The response then has the `withBody` method called on it.

According to the `RequestException` however, `getResponse` can return `null`. I'd suggest re-throwing the request exception if it does not have a response on it, but you might want this handled differently?

**Comment by lindyhopchris** [comment]
I think we're getting this because of a `ConnectException` which extends `RequestException` and definitely doesn't have a response attached to it. But I cannot see the original exception because it is *swallowed*. That's why I think re-throwing the original exception if it does not have a response is best.

I'm happy to submit a PR but would need to know how you would like it fixed?

**Comment by oscarotero** [comment]
Hi!
Yes, I think re-throwing the exception is the best solution, so it can handled in other middleware (like [error-handler](https://github.com/middlewares/error-handler) or similar.

A PR would be great. Thank you!

**Comment by lindyhopchris** [comment]
@oscarotero great, will submit a PR
